import PDFDocument from "pdfkit";

export const generateResumePDF = (resume, res) => {
  const doc = new PDFDocument({
    margin: 50,
    size: "A4",
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${resume.fullName || "Resume"}.pdf`
  );

  doc.pipe(res);

  // ===========================
  // Header
  // ===========================

  doc
    .fontSize(26)
    .fillColor("#2563eb")
    .text(resume.fullName || "Your Name", {
      align: "center",
    });

  doc.moveDown(0.5);

  doc
    .fontSize(11)
    .fillColor("black")
    .text(
      `${resume.email || ""} | ${resume.phone || ""} | ${resume.location || ""}`,
      {
        align: "center",
      }
    );

  doc.moveDown();

  // ===========================
  // Summary
  // ===========================

  if (resume.summary) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Professional Summary");

    doc.moveDown(0.3);

    doc
      .fontSize(11)
      .fillColor("black")
      .text(resume.summary);

    doc.moveDown();
  }

  // ===========================
  // Skills
  // ===========================

  if (resume.skills?.length) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Skills");

    doc.moveDown(0.3);

    resume.skills.forEach((skill) => {
      doc
        .fontSize(11)
        .fillColor("black")
        .text(`• ${skill}`);
    });

    doc.moveDown();
  }

  // ===========================
  // Education
  // ===========================

  if (resume.education?.length) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Education");

    doc.moveDown(0.3);

    resume.education.forEach((item) => {
      doc
        .fontSize(11)
        .fillColor("black")
        .text(`• ${item}`);
    });

    doc.moveDown();
  }

  // ===========================
  // Experience
  // ===========================

  if (resume.experience?.length) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Experience");

    doc.moveDown(0.3);

    resume.experience.forEach((item) => {
      doc
        .fontSize(11)
        .fillColor("black")
        .text(`• ${item}`);
    });

    doc.moveDown();
  }

  // ===========================
  // Projects
  // ===========================

  if (resume.projects?.length) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Projects");

    doc.moveDown(0.3);

    resume.projects.forEach((item) => {
      doc
        .fontSize(11)
        .fillColor("black")
        .text(`• ${item}`);
    });

    doc.moveDown();
  }

  // ===========================
  // Certifications
  // ===========================

  if (resume.certifications?.length) {
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Certifications");

    doc.moveDown(0.3);

    resume.certifications.forEach((item) => {
      doc
        .fontSize(11)
        .fillColor("black")
        .text(`• ${item}`);
    });

    doc.moveDown();
  }

  // Footer

  doc.moveDown(2);

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by Smart Job Portal AI",
      {
        align: "center",
      }
    );

  doc.end();
};